#注册到EurekaServer
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:1234@peer1:1010/eureka/,http://admin:1234@peer2:1011/eureka/,http://admin:1234@peer3:1012/eureka/
  #使用ip地址进行注册
  instance:
    prefer-ip-address: true
    #要指定服务的实例ID
    instance-id:  zuul-server:1050
server:
  port: 1050
spring:
  application:
    name: zuul-server  #服务名

zuul:
  ribbon:
    eager-load.enabled: true
  retryable: true #是否开启重试功能
  prefix: "/servers"  #统一访问前缀
  ignoredServices: "*"  #禁用掉使用浏览器通过服务名的方式访问服务
  routes:
    pay-server: "/pay/**"   #指定pay-server这个服务使用 /pay路径来访问  - 别名
    order-server: "/order/**"   #指定order-server这个服务使用 /order路径来访问
    user-server: "/user/**"   #指定user-server这个服务使用 /user
ribbon:
  MaxAutoRetries: 1 #对当前服务的重试次数
  MaxAutoRetriesNextServer: 1 #切换相同Server的次数
  OkToRetryOnAllOperations: false # 对所有的操作请求都进行重试，如post就不能重试，如果没做幂等处理，重试多次post会造成数据的多次添加或修改
  ConnectTimeout: 3000 #请求连接的超时时间
  ReadTimeout: 3000 #请求处理的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
            #如果配置ribbon的重试，hystrix的超时时间要大于ribbon的超时时间